// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efgtymqsurnqkwfwjefj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZ3R5bXFzdXJucWt3ZndqZWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzgwMDksImV4cCI6MjA3MjQxNDAwOX0.MNQ7jDK0SvYp2xQH_BU_lA2oJXRsnpgvouZ48NPP79o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});